spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
    password: 123456
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false